### ISSUE TITLE
Add default dialect

### ISSUE THREAD

**Issue by Raphtor** [aplbrain/grand#13]
In order to have drop-in compatibility with networkx, we could make the default dialect to be nx, such that `graph.nx.{method} == graph.{method}`. Duck test with nx digraph.

**Comment by j6k4m8** [comment]
Default backend?

**Comment by j6k4m8** [comment]
Ah, I think I see what you're saying. I think this is just syntax preference, right?

I usually do something like this:

```python
my_grand_graph = grand.Graph(...)
G = my_grand_graph.nx
```

`G` now has all the networkx-flavored bells and whistles as your `graph` var above:

```python
G.add_edge(1, 2)
len(G)
```

I've hesitated to add any API dialect at the "top level" like you illustrate above because it imposes some restrictions on how the user can use the package: (Why require a networkx install?) Does the `graph = grand.Graph(...).nx` solution solve this need?

**Comment by Raphtor** [comment]
Yeah that makes sense.
