### ISSUE TITLE
Use SQLbackend, how to connect to existing SQL DB file and read the graph into memory

### ISSUE THREAD

**Issue by yangyxt** [aplbrain/grand#19]
As showed in the title.

**Comment by j6k4m8** [comment]
If you have already created a graph on disk with sqlite, you can read it like this (assuming your database file is called `example-graph.sqlite`):

```python
import grand
from grand.backends import SQLBackend

G = grand.Graph(
    backend=SQLBackend(db_url="sqlite:///example-graph.sqlite", directed=True)
)
```

You can now interact with the graph through whatever dialect you like. If you want to use NetworkX-style APIs, you can list edges like this:

```python
G.nx.edges()
```

Unfortunately, there isn't currently a great way to export and import graphs between Backends yet, as this can be a super expensive operation. If your graph is relatively small, you can export nodes and edges individually into, say, a NetworkX object — like this:

```python
H = nx.DiGraph()

for node, attrs in G.nx.nodes(data=True):
    H.add_node(node, **attrs)
    
for u, v, attrs in G.nx.edges(data=True):
    H.add_edge(u, v, **attrs)
```

Then you'll have access to all the same nodes in an in-memory NetworkX object:

```python
H.nodes(data=True)
```

---

Does this answer your question?

To get you started if you don't have a sqlite graph file yet, you can create the `example-graph.sqlite` like this:

```python
G = grand.Graph(backend=SQLBackend(db_url="sqlite:///example-graph.sqlite", directed=True))
G.nx.add_edge("X", "Y")
```

**Comment by j6k4m8** [comment]
Hey @yangyxt — does this answer your question?

**Comment by AbdealiJK** [comment]
I have a similar question I'm thinking through.
I have a custom schema (with ~10 tables and multiple relationships between the tables) already present in my RDBMS. I want to create a graph from that and run cypher queries on that to perform efficient queries.

Would I be able to use grand with grand-cypher for that ?
https://github.com/aplbrain/grand-cypher

Or will it be inefficient due to the way RDBMS queries work

**Comment by j6k4m8** [comment]
Hey @AbdealiJK — curious to hear how your experiments went! Would be interested in hearing if you had to make any major changes to get things working.

**Comment by AbdealiJK** [comment]
Hi @j6k4m8 apologies I missed replying to your previous question.
So. I essentially had to create a new backend which was like a read-only backend. And in the read-only backend, I am making like 10-20 different SQL queries to pull all the relationships I need from sqlalchemy into python. I only pull the IDs.
Once i have this info, im creating a huge graph and then using it for query operations.

Differences here are:
 - I don't do a separate query to access parts of the graph - I do a constant set of queries and pull the entire graph into python
 - I cannot modify my network graph in python
 - This probably works only because my graph isn't too large, I would not have more than 10k nodes in my graph. For this, my SQL queries take no more than 1sec to fetch all the info from SQL

**Comment by j6k4m8** [comment]
Aha, that's super interesting @AbdealiJK — thank you for the update! If you think there are any good lessons-learned that we could integrate into the package, I'd love to help!

**Comment by AbdealiJK** [comment]
I think the main one for me was that a single query which creates my entire graph was much faster than I expected.
Even if I am querying just a small portion of my graph, I currently create the entire graph - because I don't want to worry about the number of queries I have to run in case I have a deep subgraph.
If there was some way for me to get the best of both - i.e. query a part and cache ... It would be cool too. But I feel like that will always be limited to iterative approaches because of the way the SQL has to be structured.
So it seems like a memory-compute tradeoff.

I would also suggest having some hooks in grand so I can customize the SQL structure I have in an existing DB.
Currently. Grand wants to manage my SQL DB for me in its efficient way. But my usecase is more like - I want to create a graph VIEW on top of my SQL DB
